include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: ignore
    prefer_interpolation_to_compose_strings: ignore
    depend_on_referenced_packages: ignore
    unnecessary_null_comparison: ignore
    unused_import: ignore
    prefer_const_declarations: ignore
    curly_braces_in_flow_control_structures: ignore
    invalid_use_of_visible_for_testing_member: ignore
    invalid_use_of_protected_member: ignore