// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0-bneti_r_6rD6n4azTuWGEeQK3huGno',
    appId: '1:725347285427:web:7a33b95fe3a9046a6c33c6',
    messagingSenderId: '725347285427',
    projectId: 'tide-forecast-app',
    authDomain: 'tide-forecast-app.firebaseapp.com',
    storageBucket: 'tide-forecast-app.firebasestorage.app',
    measurementId: 'G-EE3JCTZ3FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzm6tjGbpt-RvGUBOlLHNaKP2TH62zEg0',
    appId: '1:725347285427:android:8fedba4d5822725c6c33c6',
    messagingSenderId: '725347285427',
    projectId: 'tide-forecast-app',
    storageBucket: 'tide-forecast-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg2GpsozDgigsMOFGiJRkxzqIBzOhuEhQ',
    appId: '1:725347285427:ios:b7f019c72776a50e6c33c6',
    messagingSenderId: '725347285427',
    projectId: 'tide-forecast-app',
    storageBucket: 'tide-forecast-app.firebasestorage.app',
    iosBundleId: 'com.beigou.tideForecastApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg2GpsozDgigsMOFGiJRkxzqIBzOhuEhQ',
    appId: '1:725347285427:ios:b7f019c72776a50e6c33c6',
    messagingSenderId: '725347285427',
    projectId: 'tide-forecast-app',
    storageBucket: 'tide-forecast-app.firebasestorage.app',
    iosBundleId: 'com.beigou.tideForecastApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0-bneti_r_6rD6n4azTuWGEeQK3huGno',
    appId: '1:725347285427:web:e48322d547f7584c6c33c6',
    messagingSenderId: '725347285427',
    projectId: 'tide-forecast-app',
    authDomain: 'tide-forecast-app.firebaseapp.com',
    storageBucket: 'tide-forecast-app.firebasestorage.app',
    measurementId: 'G-RFL0GE4F8L',
  );
}

